from pyspark.sql.types import StructType, StructField, StringType, IntegerType

snowplow_schema_1 = StructType(
    [
        StructField("app_id", StringType(), True),
        StructField("platform", StringType(), True),
        StructField("etl_tstamp", StringType(), True),
        StructField("collector_tstamp", StringType(), True),
        StructField("dvce_created_tstamp", StringType(), True),
        StructField("event", StringType(), True),
        StructField("event_id", StringType(), True),
        StructField("txn_id", StringType(), True),
        StructField("name_tracker", StringType(), True),
        StructField("v_tracker", StringType(), True),
        StructField("v_collector", StringType(), True),
        StructField("v_etl", StringType(), True),
        StructField("user_id", StringType(), True),
        StructField("user_ipaddress", StringType(), True),
        StructField("user_fingerprint", StringType(), True),
        StructField("domain_userid", StringType(), True),
        StructField("domain_sessionidx", StringType(), True),
        StructField("network_userid", StringType(), True),
        StructField("geo_country", StringType(), True),
        StructField("geo_region", StringType(), True),
        StructField("geo_city", StringType(), True),
        StructField("geo_zipcode", StringType(), True),
        StructField("geo_latitude", StringType(), True),
        StructField("geo_longitude", StringType(), True),
        StructField("geo_region_name", StringType(), True),
        StructField("ip_isp", StringType(), True),
        StructField("ip_organization", StringType(), True),
        StructField("ip_domain", StringType(), True),
        StructField("ip_netspeed", StringType(), True),
        StructField("page_url", StringType(), True),
        StructField("page_title", StringType(), True),
        StructField("page_referrer", StringType(), True),
        StructField("page_urlscheme", StringType(), True),
        StructField("page_urlhost", StringType(), True),
        StructField("page_urlport", StringType(), True),
        StructField("page_urlpath", StringType(), True),
        StructField("page_urlquery", StringType(), True),
        StructField("page_urlfragment", StringType(), True),
        StructField("refr_urlscheme", StringType(), True),
        StructField("refr_urlhost", StringType(), True),
        StructField("refr_urlport", StringType(), True),
        StructField("refr_urlpath", StringType(), True),
        StructField("refr_urlquery", StringType(), True),
        StructField("refr_urlfragment", StringType(), True),
        StructField("refr_medium", StringType(), True),
        StructField("refr_source", StringType(), True),
        StructField("refr_term", StringType(), True),
        StructField("mkt_medium", StringType(), True),
        StructField("mkt_source", StringType(), True),
        StructField("mkt_term", StringType(), True),
        StructField("mkt_content", StringType(), True),
        StructField("mkt_campaign", StringType(), True),
        StructField("contexts", StringType(), True),
        StructField("se_category", StringType(), True),
        StructField("se_action", StringType(), True),
        StructField("se_label", StringType(), True),
        StructField("se_property", StringType(), True),
        StructField("se_value", StringType(), True),
        StructField("unstruct_event", StringType(), True),
        StructField("tr_orderid", StringType(), True),
        StructField("tr_affiliation", StringType(), True),
        StructField("tr_total", StringType(), True),
        StructField("tr_tax", StringType(), True),
        StructField("tr_shipping", StringType(), True),
        StructField("tr_city", StringType(), True),
        StructField("tr_state", StringType(), True),
        StructField("tr_country", StringType(), True),
        StructField("ti_orderid", StringType(), True),
        StructField("ti_sku", StringType(), True),
        StructField("ti_name", StringType(), True),
        StructField("ti_category", StringType(), True),
        StructField("ti_price", StringType(), True),
        StructField("ti_quantity", StringType(), True),
        StructField("pp_xoffset_min", StringType(), True),
        StructField("pp_xoffset_max", StringType(), True),
        StructField("pp_yoffset_min", StringType(), True),
        StructField("pp_yoffset_max", StringType(), True),
        StructField("useragent", StringType(), True),
        StructField("br_name", StringType(), True),
        StructField("br_family", StringType(), True),
        StructField("br_version", StringType(), True),
        StructField("br_type", StringType(), True),
        StructField("br_renderengine", StringType(), True),
        StructField("br_lang", StringType(), True),
        StructField("br_features_pdf", StringType(), True),
        StructField("br_features_flash", StringType(), True),
        StructField("br_features_java", StringType(), True),
        StructField("br_features_director", StringType(), True),
        StructField("br_features_quicktime", StringType(), True),
        StructField("br_features_realplayer", StringType(), True),
        StructField("br_features_windowsmedia", StringType(), True),
        StructField("br_features_gears", StringType(), True),
        StructField("br_features_silverlight", StringType(), True),
        StructField("br_cookies", StringType(), True),
        StructField("br_colordepth", StringType(), True),
        StructField("br_viewwidth", StringType(), True),
        StructField("br_viewheight", StringType(), True),
        StructField("os_name", StringType(), True),
        StructField("os_family", StringType(), True),
        StructField("os_manufacturer", StringType(), True),
        StructField("os_timezone", StringType(), True),
        StructField("dvce_type", StringType(), True),
        StructField("dvce_ismobile", StringType(), True),
        StructField("dvce_screenwidth", StringType(), True),
        StructField("dvce_screenheight", StringType(), True),
        StructField("doc_charset", StringType(), True),
        StructField("doc_width", StringType(), True),
        StructField("doc_height", StringType(), True),
        StructField("tr_currency", StringType(), True),
        StructField("tr_total_base", StringType(), True),
        StructField("tr_tax_base", StringType(), True),
        StructField("tr_shipping_base", StringType(), True),
        StructField("ti_currency", StringType(), True),
        StructField("ti_price_base", StringType(), True),
        StructField("base_currency", StringType(), True),
        StructField("geo_timezone", StringType(), True),
        StructField("mkt_clickid", StringType(), True),
        StructField("mkt_network", StringType(), True),
        StructField("etl_tags", StringType(), True),
        StructField("dvce_sent_tstamp", StringType(), True),
        StructField("refr_domain_userid", StringType(), True),
        StructField("refr_dvce_tstamp", StringType(), True),
        StructField("derived_contexts", StringType(), True),
        StructField("domain_sessionid", StringType(), True),
        StructField("derived_tstamp", StringType(), True),
        StructField("event_vendor", StringType(), True),
        StructField("event_name", StringType(), True),
        StructField("event_format", StringType(), True),
        StructField("event_version", StringType(), True),
        StructField("event_fingerprint", StringType(), True),
        StructField("true_tstamp", StringType(), True),
    ]
)


snowplow_schema = [
    "app_id",
    "platform",
    "etl_tstamp",
    "collector_tstamp",
    "dvce_created_tstamp",
    "event",
    "event_id",
    "txn_id",
    "name_tracker",
    "v_tracker",
    "v_collector",
    "v_etl",
    "user_id",
    "user_ipaddress",
    "user_fingerprint",
    "domain_userid",
    "domain_sessionidx",
    "network_userid",
    "geo_country",
    "geo_region",
    "geo_city",
    "geo_zipcode",
    "geo_latitude",
    "geo_longitude",
    "geo_region_name",
    "ip_isp",
    "ip_organization",
    "ip_domain",
    "ip_netspeed",
    "page_url",
    "page_title",
    "page_referrer",
    "page_urlscheme",
    "page_urlhost",
    "page_urlport",
    "page_urlpath",
    "page_urlquery",
    "page_urlfragment",
    "refr_urlscheme",
    "refr_urlhost",
    "refr_urlport",
    "refr_urlpath",
    "refr_urlquery",
    "refr_urlfragment",
    "refr_medium",
    "refr_source",
    "refr_term",
    "mkt_medium",
    "mkt_source",
    "mkt_term",
    "mkt_content",
    "mkt_campaign",
    "contexts",
    "se_category",
    "se_action",
    "se_label",
    "se_property",
    "se_value",
    "unstruct_event",
    "tr_orderid",
    "tr_affiliation",
    "tr_total",
    "tr_tax",
    "tr_shipping",
    "tr_city",
    "tr_state",
    "tr_country",
    "ti_orderid",
    "ti_sku",
    "ti_name",
    "ti_category",
    "ti_price",
    "ti_quantity",
    "pp_xoffset_min",
    "pp_xoffset_max",
    "pp_yoffset_min",
    "pp_yoffset_max",
    "useragent",
    "br_name",
    "br_family",
    "br_version",
    "br_type",
    "br_renderengine",
    "br_lang",
    "br_features_pdf",
    "br_features_flash",
    "br_features_java",
    "br_features_director",
    "br_features_quicktime",
    "br_features_realplayer",
    "br_features_windowsmedia",
    "br_features_gears",
    "br_features_silverlight",
    "br_cookies",
    "br_colordepth",
    "br_viewwidth",
    "br_viewheight",
    "os_name",
    "os_family",
    "os_manufacturer",
    "os_timezone",
    "dvce_type",
    "dvce_ismobile",
    "dvce_screenwidth",
    "dvce_screenheight",
    "doc_charset",
    "doc_width",
    "doc_height",
    "tr_currency",
    "tr_total_base",
    "tr_tax_base",
    "tr_shipping_base",
    "ti_currency",
    "ti_price_base",
    "base_currency",
    "geo_timezone",
    "mkt_clickid",
    "mkt_network",
    "etl_tags",
    "dvce_sent_tstamp",
    "refr_domain_userid",
    "refr_dvce_tstamp",
    "derived_contexts",
    "domain_sessionid",
    "derived_tstamp",
    "event_vendor",
    "event_name",
    "event_format",
    "event_version",
    "event_fingerprint",
    "true_tstamp",
]
